### ISSUE TITLE
Copyright is out of date

### ISSUE THREAD

**Issue by mthaddon** [canonical/landscape-docs#102]
https://docs.ubuntu.com/landscape/en/repositories has "© 2018 Canonical Ltd. Ubuntu and Canonical are registered trademarks of Canonical Ltd." in the footer - should be 2019.

**Comment by Roadmaster** [comment]
Just changing it to 2019 has other implications, I suggest reading:

https://stackoverflow.com/questions/2390230/do-copyright-dates-need-to-be-updated/2391555#2391555

And checking with legal before wholesale updating copyright dates.

**Comment by anthonydillon** [comment]
@nottrobin you may have input into this issue as you have had this discussion with legal.

**Comment by nottrobin** [comment]
Aye I spoke to legal about this a while ago.

While @Roadmaster is correct that there's no legal urgency to updating the date, it is nonetheless the company's position that we should technically update the copyright notice on a page to the year that the page was most recently updated.

Practically speaking though, since all our sites basically have global footers, this means that we should update the copyright notice on a site whenever we touch that site. And in most cases, making it dynamic so the date automatically changes on near year's day is a reasonable approximation.

Landscape docs have definitely changed this year, and so this date should technically be updated.

**Comment by BryanQuigley** [comment]
I can't find it in the code.  Where is it defined?
